version: "3"
services:
  monitoringserver:
    build: .
    restart: always
    hostname: monitoring
    container_name: monitoring
    network_mode: host
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_IDS
    logging:
      options:
        max-size: "10m"
        max-file: "3"
